# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
puts " HI "
Medicamento.create(nome: 'Lamivudina', abreviacao: '3TC', classe: 'ITRN')
Medicamento.create(nome: 'Abacavir', abreviacao: 'ABC', classe: 'ITRN')
Medicamento.create(nome: 'Síndrome de imunodeficiência adquirida', abreviacao: 'AIDS')
Medicamento.create(nome: 'Anti-retroviral', abreviacao: 'ARV')
Medicamento.create(nome: 'Atazanavir', abreviacao: 'ATV', classe: 'IP')
Medicamento.create(nome: 'Adenosina trifosfato', abreviacao: 'ATP')
Medicamento.create(nome: 'Área sob a curva', abreviacao: 'ASC')
Medicamento.create(nome: 'Zidovudina', abreviacao: 'AZT', classe: 'ITRN')
Medicamento.create(nome: 'Citocromo P450', abreviacao: 'CYP450')
Medicamento.create(nome: 'Estavudina', abreviacao: 'D4T', classe: 'ITRN')
Medicamento.create(nome: 'Zalcitabina', abreviacao: 'DDC')
Medicamento.create(nome: 'Didanosina', abreviacao: 'DDI', classe: 'ITRN')
Medicamento.create(nome: 'Ácido Desoxirribonucléico', abreviacao: 'DNA')
Medicamento.create(nome: 'Efavirenz', abreviacao: 'EFZ', classe: 'ITRNN')
Medicamento.create(nome: 'Food and Drug Administration', abreviacao: 'FDA')
Medicamento.create(nome: 'Fosamprenavir', abreviacao: 'FPV')
Medicamento.create(nome: 'Emtricitabina', abreviacao: 'FTC', classe: 'ITRN')
Medicamento.create(nome: 'Terapia anti-retroviral altamente eficaz', abreviacao: 'HAART')
Medicamento.create(nome: 'Vírus da hepatite B', abreviacao: 'HBV')
Medicamento.create(nome: 'Vírus da imunodeficiência Humana', abreviacao: 'HIV')
Medicamento.create(nome: 'Indinavir', abreviacao: 'IDV')
Medicamento.create(nome: 'Índice de massa corporal', abreviacao: 'IMC')
Medicamento.create(nome: 'Inibidores da protease', abreviacao: 'IP')
Medicamento.create(nome: 'Inibidores de Fusão', abreviacao: 'IsF')
Medicamento.create(nome: 'Inibidores da trancriptase reversa análogos de nucleosídeos', abreviacao: 'ITRN')
Medicamento.create(nome: 'Inibidores da transcriptase reversa não análogos de nucleosídeos', abreviacao: 'ITRNN')
Medicamento.create(nome: 'Líquido cefalorraquidiano', abreviacao: 'LCR')
Medicamento.create(nome: 'Lopinavir/ritonavir', abreviacao: 'LPV/r', classe: 'IP')
Medicamento.create(nome: 'Lopinavir', abreviacao: 'LPV')
Medicamento.create(nome: 'Linfócitos T', abreviacao: 'LT')
Medicamento.create(nome: 'Long terminal repeats', abreviacao: 'LTR')
Medicamento.create(nome: 'Complexo principal de histocompatibilidade', abreviacao: 'MHC')
Medicamento.create(nome: 'Nevirapina', abreviacao: 'NVP', classe: 'ITRNN')
Medicamento.create(nome: 'Organização mundial de saúde', abreviacao: 'OMS')
Medicamento.create(nome: 'Ácido Ribonucléico', abreviacao: 'RNA')
Medicamento.create(nome: 'Ritonavir', abreviacao: 'RTV')
Medicamento.create(nome: 'Sistema nervoso Central', abreviacao: 'SNC')
Medicamento.create(nome: 'Saquinavir', abreviacao: 'SQV')
Medicamento.create(nome: 'Enfuvirtida', abreviacao: 'T20')
Medicamento.create(nome: 'Terapia Anti-retroviral', abreviacao: 'TARV')
Medicamento.create(nome: 'Tenofovir disoproxil fumarato', abreviacao: 'TDF', classe: 'ITRN')
Medicamento.create(nome: 'Trascriptase reversa', abreviacao: 'TR')
Medicamento.create(nome: 'Nelfinavir', abreviacao: 'NFV', classe: 'IP')
